### ISSUE TITLE
Rename the repository to WasmTransformer

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/WasmTransformer#1]
This would match the name of the main target, so it will be easier to declare dependencies on it in `Package.swift` of other projects. ` swiftwasm/swift-wasm-transformer` is quite verbose and repetitive and requires specifying the package name explicitly in `Package.swift` when depending on it.

**Comment by kateinoigakukun** [comment]
I prefer to use hyphen joined form because apple's official packages use that form. `wasm-transformer`

**Comment by MaxDesiatov** [comment]
Yeah, but their package name matches the repository name, so you still have to disambiguate it when specifying target dependencies. With `WasmTransformer` repository no disambiguation would be needed at all. Their convention was probably dictated by how they name repositories in their organization, but I don't think it works well with SwiftPM. My thinking is that we shouldn't follow their convention if it doesn't bring any benefits.

**Comment by MaxDesiatov** [comment]
Thanks for sorting it out!
